CREATE TABLE IF NOT EXISTS metrics (
    id VARCHAR(255) NOT NULL,
    type VARCHAR(20) NOT NULL,
    delta BIGINT,
    value DOUBLE PRECISION,
    metric_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    UNIQUE (id, type)
);